version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: test
          command: ls

